services:
  backend:
    build:
      context: ./backend
    environment:
      MINI_SQS_LOG_PATH: /app/data/queue.log
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/app/data
    networks:
      - mini-sqs-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
      - prometheus
    networks:
      - mini-sqs-network

  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - backend
    networks:
      - mini-sqs-network

networks:
  mini-sqs-network:

volumes:
  backend-data:
  prometheus-data:
